### PR TITLE
Version 0.0.47; avoid pinning old Rust crates

### PR DESCRIPTION
**Pull request by pjkundert**

### CODE REVIEW

**Comment by pjkundert** [comment]
OK, @freesig, I've used the release process to produce this, and updated a few other crates that were causing multiple old rust crates to be pulled into holochain/holochain.

**Comment by maackle** [comment]
@pjkundert, I believe the versions for this repo's crates should get bumped *during* the release, not before, i.e. your second commit is unnecessary. Also, I have another PR that needs to go into the next release, 0.0.47. So, I will cherry-pick your first commit and remove the version bump in config.nix, and combine that with my other PR.

**Comment by maackle** [comment]
@pjkundert, this is what I plan to merge: https://github.com/holochain/holochain-serialization/pull/37

**Comment by pjkundert** [comment]
Thanks, @maackle!

**Pull request closed without merging**
